language: node_js
node_js:
  - "6"
branches:
  only:
    - master

env:
  - DATABASE_URL=postgres://travis@localhost/vynl_test


before_script:
  - psql -c 'create database vynl_test;' -U travis

services:
  - postgresql

addons:
  postgresql: "9.4"

script:
  - npm run ci
